# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 原力引火
email: yuanli.info@gmail.com
description: > # 随便说说、讨论电影、分享书籍，交流思想的小空间。
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://www.yuanli.info" # the base hostname & protocol for your site
url: "http://127.0.0.1:3666"
port: 3666
twitter_username: honolily
github_username:  honolily

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About us
    url: /about

collections:
  - cursos

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
